title: Insom Thinks
author: Insomnyx
email: insomneedssleep@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is where all my thoughts will go. I will eventually add a comment 
  section to see what people think about them. Then perhaps add a way for
  other people to put their thoughts here as well.

# social links
twitter_username: AkumaKaishi # DO NOT include the @ character, or else the build will fail!
github_username:  m-lara2020 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
