title: Art of the Archives
author: Insomnyx
email: insomneedssleep@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This page is separate from the original page Archives of Our Own (AO3)
  and is being used as a way to practice website building in a similar
  style as the original page. In no way are we trying to take credit or
  copy what AO3 has built for themselves. If they were to contact us
  about taking this page down, we will do so. 
  Thank you for your understanding.

# social links
twitter_username: AkumaKaishi # DO NOT include the @ character, or else the build will fail!
github_username:  m-lara2020 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
